# Generated by Django 4.2 on 2024-01-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='title')),
                ('image', models.ImageField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, upload_to='categories/title/%Y/%m/%d', verbose_name='image')),
            ],
        ),
    ]
