# Generated by Django 5.0.2 on 2024-02-29 19:22

import catalog.models
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('profile_app', '0005_alter_profile_avatar_alter_seller_logo'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('image', models.ImageField(upload_to=catalog.models.product_images_directory_path, verbose_name='images')),
                ('is_limited', models.BooleanField(default=False, verbose_name='is_limited')),
                ('free_delivery', models.BooleanField(default=True, verbose_name='free_delivery')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='profile_app.seller')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
