# Generated by Django 5.0.2 on 2024-03-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_characteristic_product_review_recentlyviewedproducts_and_more'),
        ('catalog', '0002_product_price'),
    ]

    operations = [
    ]
