# Generated by Django 5.0.2 on 2024-03-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_image_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='popularity'),
        ),
    ]
