# Generated by Django 4.2 on 2024-03-07 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_remove_product_image_alter_product_description'),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('fio', models.CharField(max_length=50, verbose_name='fio')),
                ('delivery_type', models.CharField(choices=[('f', 'free_delivery'), ('p', 'payed_delivery'), ('sd', 'self-delivery')], default='sd', max_length=3, verbose_name='delivery_type')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='city')),
                ('address', models.TextField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('payment_type', models.CharField(choices=[('c', 'card'), ('ch', 'cash')], default='c', max_length=3, verbose_name='payment_type')),
                ('payment_status', models.CharField(choices=[('p', 'paid'), ('unp', 'unpaid')], default='unp', max_length=3, verbose_name='payment_status')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='total_amount')),
                ('payment_id', models.CharField(max_length=50, verbose_name='payment_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order_app.order', verbose_name='order_item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.seller', verbose_name='seller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
