# Generated by Django 4.2 on 2024-01-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profiles/<function Profile.get_email at 0x7f76b6839f80>/%Y/%m/%d', verbose_name='profile avatar'),
        ),
    ]
