# Generated by Django 4.2 on 2024-02-16 15:04

from django.db import migrations, models
import profile_app.models.profile
import profile_app.models.seller


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_alter_profile_avatar_alter_profile_user_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=profile_app.models.profile.profile_images_directory_path, verbose_name='profile avatar'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, upload_to=profile_app.models.seller.seller_images_directory_path, verbose_name='Logotype'),
        ),
    ]
