# Generated by Django 5.0.2 on 2024-03-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_alter_profile_avatar_seller'),
        ('profile_app', '0005_alter_profile_avatar_alter_seller_logo'),
    ]

    operations = [
    ]
