# Generated by Django 4.2 on 2024-01-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='username')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that username already exists.'}, max_length=60, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='middle name')),
                ('activation_key', models.CharField(blank=True, max_length=60)),
                ('activation_name_set', models.CharField(blank=True, max_length=60)),
                ('is_activation_key_expires', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
