# Generated by Django 4.2 on 2024-02-20 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_activation_key_expires',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_will_expires',
            field=models.DateField(default=datetime.date(2024, 2, 22), verbose_name='date of creation activation key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с таким email уже существует'}, max_length=60, unique=True, verbose_name='email'),
        ),
    ]
