# Generated by Django 4.2 on 2024-02-26 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_user_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_will_expires',
            field=models.DateField(default=datetime.date(2024, 2, 28), verbose_name='date of creation activation key'),
        ),
    ]
